export enum AttrTypeId {
    Impact = 1,
    Slash = 2,
    Physical = 3,
    Energy = 4,
    Volt = 5,
    Gravity = 6,
    Fire = 7,
    Ice = 8,
    Sword = 9,
    Hammer = 10,
    Spear = 11,
    Dagger = 12,
    HandGun = 13,
    Rifle = 14,
    Bazooka = 15,
    Twin = 16,
    Sniper = 17,
    Close = 18,
    Shot = 19,
    HP = 20,
    DEF = 21,
    None = 22,
}
